// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.EF.EF.dbDemoContext;

public partial class TblCustomerCustomerDemo
{
    public string CustomerId { get; set; }

    public string CustomerTypeId { get; set; }
}