// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.EF.EF.dbDemoContext;

public partial class TblEmployeeTerritory
{
    public int EmployeeId { get; set; }

    public string TerritoryId { get; set; }
}