// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.EF.EF.dbDemoContext;

public partial class TblRegion
{
    public int RegionId { get; set; }

    public string RegionDescription { get; set; }
}